# Note: when adding a new hook, run `pre-commit run --all-files`
# to check it against all files in the repo and commit the changes it makes.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.2.1
    hooks:
      - id: sqlfluff-fix
        additional_dependencies: ['dbt-bigquery','sqlfluff-templater-dbt']
      - id: sqlfluff-lint
        # For dbt projects, this installs the dbt "extras"
        additional_dependencies: ['dbt-bigquery','sqlfluff-templater-dbt']
  - repo: https://github.com/offbi/pre-commit-dbt
    rev: v1.0.0
    hooks:
      - id: dbt-compile
        args: [ "--cmd-flags", "++profiles-dir", ".github/.dbt", "--"]
      - id: check-script-semicolon
      - id: check-script-ref-and-source
      - id: check-model-has-properties-file

default_language_version:
    # force all unspecified python hooks to run python3
    python: python3
