version: 2

models:
  - name: dwr_groups
    description: ""
    columns:
      - name: group_id
        description: "Unique identifier for this group"

      - name: group_name
        description: "Name of the grou"

      - name: description
        description: "Description of the group"

      - name: city
        description: "Name of the city where the group resides"

      - name: latitude
        description: "Latitude of the place where the group resides"

      - name: longitude
        description: "Longitude of the place where the group resides"

      - name: time_group_created
        description: "Timestamp of when the group was created"

      - name: group_url
        description: "Link to the group’s homepage"

      - name: topics
        description: "Array of topics that this group discusses or otherwise associates with"
